language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- npm install -g gulp
- bower install
script: gulp
before_deploy:
- cd dist
deploy:
  provider: heroku
  api_key:
    secure: pBASfZlZxNGSubLc+7BM1Xh7f/u2CVGF4HpbFG4UU0KbS1TsfOt6vj6EsCADy5U0aAHaiNKQxVYykGO9+7X9GuVb4ING6iBOYMEsv9wFWXz8I58wcXiljhxJgEMK+t9GfuMfPo+LJWdfB6lQI0ffZmG6G3xAQsCpjdZfQJk05VpAiXxq6HJzGAZ/rdjQHidHhbNL7f0En8RdIWpfnsEJZclxGgeTdvLcLnFzo5/JYtXYBLo6uBqKUKWX2VX0BxjUF5rWhQfyb1JYi0jTa8UkyP/zd+pKy1AYNOM3UevtGFztIxlPa8bg/kMfDfutb/JeUK48A/DteY7A3/1XUSoRiC5sbaf97x6nZyeUBdi/eHJCMJ9NDTDW5bs7/zWIYIItrZh+9OsroF0IqnybxnL/fMGiTlWAfXCE3L6M9hjllHjDXi1498O4FQiDcDY5JAGaAxihiYyf5tv4alH6W6uvPlTWrLjXvyZMc+DQYZESX9J/X76qp/7FDiEbN7WJTfcKQdINSShnbRAGd4Jhmqv9eqBahAKMyXl8sZeT/9lgQD9gicWjWdIQVjCRDKS8f+iZ5YCssRZMkuc3hAyN0lXpSlnN7Ktv3CorL1mjpN/GbbJ4S8jA34Fg1c+DW9Gkr37DHMWPBfqW9uNHcL4vYecvtDCZTNfOsXy6Xk/excUAPnQ=
  app: advancedaccounting
  on:
    repo: harmandeol/advancedaccounting
